### ISSUE TITLE
Normalize var names to reduce flakiness

### ISSUE THREAD

**Issue by achreto** [verus-lang/verus#654] opened 2023-06-28 19:07 UTC
With the recent switch to use the normal `std::vec::Vec` the way to access elements in the vector has changed. 
In particular, `vec.index(i)` is replaced with `vec[i]` 

There could be an issue with reasoning about the returned value. In the [NR](https://github.com/verus-lang/verus-systems-code/compare/nr-resource-limit?expand=1) proofs, we access the operations vector:

```
log_entries[i]@.value.op == operations[i as int]
```

This unfortunately results in exceeding the `rlimit`. Adding the `&` makes the proof go through: 

```
log_entries[i]@.value.op == &operations[i as int]
```

**Comment by tjhance** [comment] 2023-06-29 02:20
@achreto I haven't been to able to reproduce. What version of verus are you using, and what exact command are you running?

Even though I couldn't reproduce the specific error, the AIR code does change between files. Specifically, all the VIR identifiers change; that could easily cause "flakiness". I also think it would be a good idea to fix, even if I haven't confirmed it's the issue here.

(The reason the VIR identifiers change is that they depend on HIR node IDs, and the addition of a single & node bumps all the IDs by 1.)

 - [ ] Normalize variable names in rust->VIR conversion rather than keeping the HIR node IDs. (We still need to use them to disambiguate, but we can replace them with smaller ints: e.g., change x~42 and x~99 to x~1 and x~2)

**Comment by achreto** [comment] 2023-07-03 20:42
Sorry for the delay in responding. The command is the following

```
../verus/source/tools/rust-verify.sh --release nr/src/main.rs --arch-word-bits 64  
```

Output (re-run today): 

```
note: while loop has been running for 2 seconds
   --> nr/src/exec/log.rs:868:13
    |
868 | /             while idx < nops
869 | |                 invariant
870 | |                     self.wf(),
871 | |                     0 <= idx <= nops,
...   |
943 | |                 idx = idx + 1;
944 | |             }
    | |_____________^

error: while loop: Resource limit (rlimit) exceeded; consider rerunning with --profile for more details
   --> nr/src/exec/log.rs:868:13
    |
868 | /             while idx < nops
869 | |                 invariant
870 | |                     self.wf(),
871 | |                     0 <= idx <= nops,
...   |
943 | |                 idx = idx + 1;
944 | |             }
    | |_____________^

```
Version:

```
Verus
  Platform: linux_x86_64
  Version: 0.2023.06.30.6e3d21d
  Profile: release
```

Z3 version is 4.12.2. (assuming it always takes the one obtained through the script)

**Comment by tjhance** [comment] 2024-02-28 00:27
fixed in https://github.com/verus-lang/verus/pull/1003

**Closed by tjhance** 2024-02-28 00:27 UTC
Labels: incompleteness
