### ISSUE TITLE
Restriction in recursing under closure

### ISSUE THREAD

**Issue by gancherj** [verus-lang/verus#590] opened 2023-06-07 20:05 UTC
Hi all - we are currently working on a verification project involving a tree datatype that uses `FnSpec` to define the branching structure, and are finding it difficult to define traversals over these trees. 

Playground link here: https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=a6cf688c4eb8d8066bae48a4b64c32b9

When I run the above, I get the following error:
```
error: recursion not allowed here
  --> /playground/src/main.rs:13:45
   |
13 |         Tree::Branch(f) => Tree::Branch(|x| addone(f(x))),
   |                                             ^^^^^^^^^^^^
```

The error we reach in Verus is here: https://github.com/verus-lang/verus/blob/2cae5690674b30c123c83ac5126c4160d1d1bc61/source/vir/src/recursion.rs#L367

Is it possible to soundly extend Verus so that (simple uses of) recursion inside of closures is allowed?

**Comment by tjhance** [comment] 2023-06-07 20:11
we expect this to be possible after #570 is merged in. You can go ahead and try the branch and see if it helps for your case

**Comment by tjhance** [comment] 2023-06-07 20:12
Actually sorry, I think I misunderstood what the issue is

**Comment by pratapsingh1729** [comment] 2023-06-07 22:02
I'm sure I am missing something fairly obvious, but what are the soundness issues that arise with recursion under closures?

**Comment by jaybosamiya** [comment] 2023-06-07 23:05
Looking at the `git blame` for that bit, it seems to be an almost 2 year old commit by @Chris-Hawblitzel (cd610996e17b31de515ccaf4d53a1509e0a7a70c), so Chris can probably explain the specific decision itself better (from a quick look, it simply seems like _all_ recursion under closures is stopped, purely to keep things simple when implementing closures; however, some recursion would likely still be sound, just requires more effort to track and manage, and hasn't been needed just yet).

Nonetheless, looking further at this particular example, _even if_ there was better support for recursion with closures in Verus, this might not be ok. In particular, there is nothing that requires that `f` produces a "smaller" tree than what it took in, and thus `t` itself is not necessarily decreasing in invocations to `addone`, and thus it _could_ be non-terminating, and thus if allowed, the definition here would not be sound.

**Comment by Chris-Hawblitzel** [comment] 2023-06-07 23:48
In fact, I was just discussing this last week with Nikhil Swamy since it was a similar topic to https://github.com/verus-lang/verus/pull/570 .  Both F* and Dafny allow recursion inside closures.  I think Verus should too, and it should be straightforward to implement.

**Comment by pratapsingh1729** [comment] 2023-06-08 01:06
@jaybosamiya @Chris-Hawblitzel Thanks so much! It might be helpful in our situation to have recursion under closures like this example.

@jaybosamiya Not sure I follow what you're saying in your second paragraph. The `f` comes from within the input tree `t`, so if `f(x)` produces some large tree, then (in some moral sense) that large tree should be a subtree of `t`, since `t = Branch(f)`. My understanding of `FnSpec` is that it is the type of pure deterministic terminating functions, so for all `x`, `f(x)` will terminate and produce a valid `tree`. Is this correct?

**Comment by jaybosamiya** [comment] 2023-06-08 18:55
Ah apologies, looks like I misunderstood what could happen, and indeed I don't think this breaks down directly; tracing back to why I thought it breaks down, the best approximation I can tell is that I somehow misread the `addone(f(x))` as `addone(f(x + 1))`?? Because if that is done, then running `addone(Tree::Branch(treelist))` where `treelist` is the function below, would be bad (`treelist` is also currently rejected by Verus btw, but otherwise is a terminating spec function)

```rs
spec fn treelist(x: int) -> Tree
  decreases x
{
   if x <= 0 {
       Tree::Ret(x)
   } else {
       Tree::Branch(|y| treelist(x-1))
   }
}
```

Given that there isn't a `+1` during the recursion, I don't think the actual problem that I was thinking of holds.

Apologies for the confusion

**Comment by Chris-Hawblitzel** [comment] 2023-06-09 15:32
Ok, recursion inside closures is now allowed, as in Dafny and F*.  This change is in the `main` branch.  I also pushed the change to the `is_smaller_than` branch for the pull request https://github.com/verus-lang/verus/pull/570 that @tjhance mentioned.  In this branch, the `addone` example succeeds.

However, I'm not yet confident that the way the `is_smaller_than` branch is currently implementing `forall x, f(x) << F(f)` is correct.  I've been asking around to see how F* and Dafny ( https://app.gitter.im/#/room/#dafny-lang_community:gitter.im ) approach this, and there are some subtleties ( https://github.com/FStarLang/FStar/pull/2954 ) that may or may not be relevant to Verus.  Basically, the question is whether `forall x, f(x) << F(f)` is meaningfully more restrictive than `forall x, f(x) << f` and whether this matters.

**Comment by utaal** [comment] 2023-06-28 14:53
@Chris-Hawblitzel: we can pick this up again later if the constraints are too strict and they need to be relaxed while staying sound.

**Closed by utaal** 2023-06-28 14:53 UTC
