### ISSUE TITLE
compiler panic with pervasive::Option unwrap

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#372] opened 2023-02-08 18:59 UTC
[snapshot here](https://github.com/vmware-labs/verified-betrfs/tree/panicked_compiler)
`rust-verify.sh Splinter/src/lib.rs`
gives
![verus_error_720](https://user-images.githubusercontent.com/1816420/217626220-c2f1a57f-db08-4cdf-adf2-2027ca39b61d.png)

**Comment by jonhnet** [comment] 2023-02-08 18:59
The offending line was this unwrap() of a pervasive::Option:
https://github.com/vmware-labs/verified-betrfs/blob/panicked_compiler/Splinter/src/coordination_layer/CoordinationSystem_v.rs#L143
replacing the .unwrap() with .get_Some_0() works around the panic.

**Comment by jonhnet** [comment] 2023-02-08 18:59
Ah, if the unwrap isn't buried inside the struct constructor, we get a sane and verus-related error: cannot call function with mode exec

**Comment by tjhance** [comment] 2023-02-09 02:16
Okay first of all, the reason for the problem is that unwrap() returns a `&Known`, while Rust is expecting a `Known`. So if you do `.. *pre.ephemeral.unwrap()` with the dereference `*` in there, it will pass type-checking (and then fail Verus mode-checking).

The crash, though turns out to be a _rustc_ bug, not a Verus bug. It fails in type-checking, before we even do anything in VIR.

Here's a minimal crashing example:

```rust
pub enum Foo<A> {
    None,
    Some(A)
}

impl<A> Foo<A> {
    pub fn unwrap(&self) -> &A
    {
        unimplemented!();
    }
}

pub struct Known {
    progress: u16,
    map_lsn: u16,
}

pub fn Recover(ephemeral: Foo<Known>) {
    let update_tmp_ephemeral = Known{map_lsn: 0, ..ephemeral.unwrap()};
}
```

However, this bug has been fixed on stable rust. It only shows up because Verus is currently on 1.58 which is kinda old at this point. So the problem will eventually go away when we update Rust.

**Closed by tjhance** 2023-02-09 02:16 UTC
