### ISSUE TITLE
Internal error: generated ill-typed AIR code

### ISSUE THREAD

**Issue by jaylorch** [verus-lang/verus#523] opened 2023-04-15 01:05 UTC
The verifier crashed. You can reproduce the following error by checking out the `verus-crash` branch of the `verus-systems-code` repo, at `https://github.com/verus-lang/verus-systems-code/tree/verus-crash`, and running `scons --verus-path=<your verus path>` from the `ironfleet-comparison` directory.
```
thread 'rustc' panicked at 'internal error: generated ill-typed AIR code: error 'in equality, left expression has type tuple%0. and right expression has different type vstd!vec.Vec<lib!cmessage_v.CPacket.>.' in expression '(= tmp%7@ (%Poly%vstd!vec.Vec<lib!cmessage_v.CPacket.>. tmp%5@))'', rust_verify/src/verifier.rs:375:21
```

**Comment by tjhance** [comment] 2023-04-15 02:26
Not entirely sure what the problem is yet. For anyone in the future, a minimized repro is:

```rust
struct X {}

fn gha() -> Vec<X> { Vec::new() }

fn test(o: Option<Option<int>>) -> (sent_packets: Vec<X>)
    ensures sent_packets.view().len() == 0
{
    match o {
        Some(m) =>
            match m {
                Some(_) => {
                    return gha();
                }
                _ => {
                    assume(false);
                    unreached()
                },
            },
        _ => {
            assert(false);
            unreached()
        }
    }
}
```

**Comment by jaylorch** [comment] 2023-04-15 02:29
Thanks for minimizing it, Travis!

**Comment by Chris-Hawblitzel** [comment] 2023-04-15 02:59
Ok, it should be fixed by https://github.com/verus-lang/verus/commit/6751110a48c3ea0fdd5752e48a5a0594269f457f .

**Comment by jaylorch** [comment] 2023-04-15 04:26
Wow, that was fast. Thanks!

**Closed** 2023-04-16 12:14 UTC
Labels: bug
