### ISSUE TITLE
Panic + hang on `--expand-errors`

### ISSUE THREAD

**Issue by jaybosamiya** [verus-lang/verus#908] opened 2023-11-17 01:18 UTC
Consider this code:
```rs
use vstd::prelude::*;

verus! {

trait Tau {
    spec fn foo(&self, n: &Self) -> bool;
    proof fn bar(&self, n: &Self)
        ensures
            n.foo(self);
}

struct T;

impl Tau for T {
    spec fn foo(&self, n: &Self) -> bool;
    proof fn bar(&self, n: &Self);
}

} // verus!

fn main() {}
```

It panics, and then hangs (infinite loop? deadlock?) after the panic happens on the thread, but _only_ when run with `--expand-errors`:
```console
$ verus wat.rs
verus wat.rs
error: postcondition not satisfied
  --> wat.rs:18:34
   |
10 |             n.foo(self);
   |             ----------- failed this postcondition
...
18 |     proof fn bar(&self, n: &Self);
   |                                  ^ at the end of the function body

error: aborting due to previous error

verification results:: 0 verified, 1 errors

$ verus --expand-errors wat.rs
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:715:21:
internal error: generated ill-typed AIR code: error 'error 'error 'use of undeclared variable Self%&.' in expression 'Self%&.'' in expression '(wat!Tau.foo.? Self%&. Self%& n~4@ self~2@)'' in expression '(%B (wat!Tau.foo.? Self%&. Self%& n~4@ self~2@))'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: postcondition not satisfied
  --> wat.rs:18:34
   |
10 |             n.foo(self);
   |             ----------- failed this postcondition
...
18 |     proof fn bar(&self, n: &Self);
   |                                  ^ at the end of the function body

```

Tested on
```console
$ verus --version
Verus
  Version: 0.2023.11.15.825487c
  Profile: release
  Platform: macos_aarch64
  Toolchain: 1.73.0-aarch64-apple-darwin
```

---

Out of the two things, the hang is particularly annoying, since it made minimization of the test case way more difficult; fixing the panic will presumably fix _this_ particular hang, but will likely just kick the bucket down the line further till the next similar kind of panic that will be painful to minimize again, so it might be a good idea to investigate and fix the hang. Given that the panic is on a separate thread, I assume this is likely due to the main thread waiting on something?

**Comment by utaal** [comment] 2023-11-17 09:04
Thank you for the report. Verus should now panic when one of its worker thread panics.

I believe this has the same root cause as https://github.com/verus-lang/verus/issues/859.
I'm going to close this in favor of that one and move the smaller repro over. Thank you for minimizing it!

**Closed by utaal** 2023-11-17 09:04 UTC

**Comment by jaybosamiya** [comment] 2023-11-17 17:57
Thanks <3
