### ISSUE TITLE
Probably-unhelpful error hint about closed fns

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#745] opened 2023-08-15 16:13 UTC
I came across this hint and realized it's anti-helpful. Sure, the fn isn't open, but opening it probably wouldn't help much, either, because it's uninterpreted.

```
   ::: /home/jonh/verus/source/pervasive/set.rs:58:5
    |
58  |     pub spec fn contains(self, a: A) -> bool;
    |     ---------------------------------------- Note: this function is closed at the module boundary
```

**Comment by utaal** [comment] 2023-08-15 16:58
Thanks for the report. Closing as duplicate of https://github.com/verus-lang/verus/discussions/387#discussioncomment-5679193

**Closed by utaal** 2023-08-15 16:58 UTC
