### ISSUE TITLE
ast_simplify doesn't respect evaluation order

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verus#115] opened 2022-03-28 22:59 UTC
```rust
#[allow(unused_imports)]
use builtin::*;
mod pervasive;
use pervasive::*;

struct Foo {
    pub a: bool,
    pub b: bool,
    pub c: bool,
}

fn do_mut(x: &mut u64) -> bool {
    ensures(|b: bool| *x == 19 && b == true);
    *x = 19;
    true
}

fn get_bool() -> bool {
    requires(false);
    false
}

fn same_foo(foo: Foo) -> Foo {
    foo
}

fn main() {
    let foo = Foo { a: false, b: false, c: false };

    let mut x = 5;

    let bar = Foo {
        a: do_mut(&mut x) || get_bool(),
        ..same_foo(foo)
    };
}
```

Here, we have:

```
error: precondition not satisfied
  --> l2.rs:33:30
   |
19 |     requires(false);
   |              ----- failed precondition
...
33 |         a: do_mut(&mut x) || get_bool(),
   |                              ^^^^^^^^^^
```

Note that `do_mut` returns `true`, so `get_bool()` should never be called; yet, the precondition fails.

Here's the relevant AIR (note that `get_bool()` is called _before_ `do_mut`. This violates both short-circuiting _and_ evaluation order.

```
;; Function-Def crate::main
 (check-valid
  (declare-const tmp%1@ Bool)
  (declare-const tmp%%2@ Bool)
  (declare-const tmp%%1@ Foo.)
  (declare-const foo@ Foo.)
  (declare-var x@ Int)
  (declare-const bar@ Foo.)
  (axiom fuel_defaults)
  (block
   (assume
    (= foo@ (Foo./Foo (%B (B false)) (%B (B false)) (%B (B false))))
   )
   (assume
    (= x@ 5)
   )
   (block
    (assert
     ("precondition not satisfied")
     (req%get_bool.)
   ))
   (block)
   (block
    (snapshot snap%CALL)
    (havoc x@)
    (assume
     (ens%do_mut. (old snap%CALL x@) x@ tmp%1@)
   ))
   (assume
    (= bar@ (Foo./Foo (%B (B (or
         tmp%1@
         tmp%%2@
       ))
      ) (%B (B (Foo./Foo/b (%Poly%Foo. (Poly%Foo. tmp%%1@))))) (%B (B (Foo./Foo/c (%Poly%Foo.
          (Poly%Foo. tmp%%1@)
 )))))))))
```

**Comment by tjhance** [comment] 2022-03-28 23:06
aha, here's version that violates soundness:

```rust
#[allow(unused_imports)]
use builtin::*;
mod pervasive;
use pervasive::*;

struct Foo {
    pub a: u64,
    pub b: bool,
    pub c: bool,
}

fn do_mut(x: &mut u64) -> u64 {
    ensures(|b: u64| *x == 1 && b == 1);
    *x = 1;
    1
}

fn get_bool() -> bool {
    requires(false);
    false
}

fn same_foo(foo: Foo) -> Foo {
    foo
}

fn main() {
    let foo = Foo { a: 0, b: false, c: false };

    let mut x = 5;

    let bar = Foo {
        a: (do_mut(&mut x) + (x * 2)), // should evaluate to 1 + 1 * 2 = 3
        ..same_foo(foo)
    };

    // bar.a should be 3
    assert(bar.a == 11); // this incorrectly passes
}
```

**Comment by utaal** [comment] 2022-03-29 14:05
@tjhance noted: "the problem is if we have `call(&mut t.call(...), call2(...));` then if we don't temp the first argument, we can't temp the second argument either"

**Comment by tjhance** [comment] 2022-03-29 14:23
There are a handful of issues here:

**One.** The simplest issue is that this case in ast_simplify doesn't handle boolean operators that short-circuit:

```rust
        ExprX::Binary(op, e1, e2) => {
            let (stmts, exprs, contains_loc) =
                small_loc_or_temp_exprs(state, &[e1.clone(), e2.clone()]);
            let mut exprs = exprs.into_iter();
            let expr1 = exprs.next().unwrap();
            let expr2 = exprs.next().unwrap();
            contains_loc.then(|| (stmts, expr.new_x(ExprX::Binary(*op, expr1, expr2))))
        }
```

Although it's hard to make a simple test case to illustrate the problem without running into the below issues as well:

**Two.** The `small_loc_or_temp` function is designed to avoid creating temp variables for certain expressions. However, it seems to be mis-firing in some cases. In the snippets I posted above, for example, Verus refuses to temp the expression `do_mut(&mut x)` even though it should be safe to do so.

**Three.** Even when it works with what seems to be the original intent, there are still some problems, for example, in `call(&mut t.call(...), call2(...));`, which Andrea posted above. In this case, we can't fundamentally get around the fact `call2(...)` has to evaluate in between the `t.call` and the use of its mutable reference.

**Comment by tjhance** [comment] 2022-03-29 14:39
Here are some related cases, originally from https://github.com/secure-foundations/verus/issues/102

The problem with these cases is that since the call doesn't get temp'ed, it ends up getting duplicated.

**Case 1.**

```rust
#[allow(unused_imports)] use builtin::*;
#[allow(unused_imports)] use builtin_macros::*;
mod pervasive;
#[allow(unused_imports)] use crate::pervasive::*;

#[proof]
#[verifier(external_body)]
#[verifier(returns(proof))]
fn foo(#[proof] x: &mut int) -> (int, int)
{
    ensures(|ret: (int, int)|
        { let (a, b) = ret;
            a + b == (*x)
        }
    );

    unimplemented!();
}

fn bar(#[proof] x: int) {
    #[proof] let mut x = x;
    #[proof] let (a, b) = foo(&mut x);
    assert(a + b == x); // THIS LINE FAILS
}

fn main() { }
```

```
   (assume
    (= x$1@ x@)
   )
   (block
    (snapshot snap%CALL)
    (havoc x$1@)
    (assume
     (ens%foo. (old snap%CALL x$1@) x$1@ tmp%1@)
   ))
   (assume
    (= a@ (%I (tuple%2./tuple%2/field%0 (%Poly%tuple%2. (Poly%tuple%2. tmp%1@)))))
   )
   (block
    (snapshot snap%CALL)
    (havoc x$1@)
    (assume
     (ens%foo. (old snap%CALL x$1@) x$1@ tmp%2@)
   ))
   (assume
    (= b@ (%I (tuple%2./tuple%2/field%1 (%Poly%tuple%2. (Poly%tuple%2. tmp%2@)))))
   )
   (assume
    (= tmp%3@ (= (+ a@ b@) x$1@))
   )
```

**Case 2** (code wrongly verifies)

```rust
#[allow(unused_imports)] use builtin::*;
#[allow(unused_imports)] use builtin_macros::*;
mod pervasive;
#[allow(unused_imports)] use crate::pervasive::*;

fn foo(x: &mut bool) -> (u8, u8)
{
    ensures(|ret: (u8, u8)|
        { (*x) == ! *old(x) }
    );

    *x = ! *x;
    (0, 0)
}

fn bar(#[proof] x: int) {
    let mut x = true;
    let (a, b) = foo(&mut x);
    assert(x == true); // passes, but `x` should be `false` here
}

fn main() { }
```

**Comment by utaal** [comment] 2022-03-29 15:44
Fundamentally `small_loc_or_temp` should avoid temp-ing expressions that represent "locations" (i.e. left-hand-sides). This is because there is (intentionally) no concept of an `&mut` variable in VIR, and for example we conceptually treat `&mut` parameters by turning them into an in-parameter and an out-parameter.

**Comment by tjhance** [comment] 2022-03-29 15:49
Here's another issue (maybe latent, given the unimplemented features). From ast_simplify:

```rust
fn is_small_expr(expr: &Expr) -> bool {
    match &expr.x {
        ExprX::Const(_) | ExprX::Var(_) | ExprX::VarAt(..) => true,
        ExprX::Unary(UnaryOp::Not | UnaryOp::Clip(_), e) => is_small_expr(e),
        ExprX::UnaryOpr(UnaryOpr::Box(_) | UnaryOpr::Unbox(_), e) => is_small_expr(e),
        ExprX::Loc(_) => panic!("expr contains a location"),
        _ => false,
    }   
}
```

I believe the correctness criterion for `is_small_expr` should be that it returns `true` only if the expression is pure (no side-effects) and only if its evaluation is not affected by side-effects. However, this returns `true` for a `Var(...)` which can be assigned to.

So there might be a problem in something like:

```
let mut x = ...;
foo(x, { x = ...; ... });
```

If the block gets hoisted up, then the `x` has to get hoisted up too.

**Comment by utaal** [comment] 2022-03-29 15:52
I don't think this is an issue. With the currently implemented features, `Var` should never be assigned to (if it is, it's a bug). Assignees should always be `VarLoc`s inside a `Loc` or in a position that's implicitly a left-hand-side.

**Comment by tjhance** [comment] 2022-03-29 15:58
I think it's a future issue. In order to handle a block expression in this position, we will need to hoist the block's statements. Those might contain an assign which contains a Loc.

**Comment by utaal** [comment] 2022-03-30 09:30
The `let (a, b) = ` cases are now patched. But I'm sure there are more cases I'm missing; I'll look into this more after I'm done with `field-update`.

**Comment by utaal** [comment] 2022-04-06 06:17
I think #97 may have patched all the unsoundness we were aware of, but I’ll keep this open until we add some more evaluation order tests.

**Closed** 2024-03-10 08:01 UTC
Labels: test-coverage
