### ISSUE TITLE
Ill-typed AIR for unit variable when trait execution

### ISSUE THREAD

**Issue by jaybosamiya** [verus-lang/verus#497] opened 2023-04-10 18:43 UTC
Consider:
```rs
use vstd::prelude::*;

verus! {

    trait Foo {
        exec fn foo(&self);
    }

    struct X;

    impl Foo for X {
        exec fn foo(&self) {
            // do nothing
        }
    }

    exec fn bar() {
        let z: X = X;
        let x: () = z.foo();
    }

}

fn main() {}
```

Produces:
```console
$ rust-verify.sh --release a.rs
note: verifying root module

thread 'rustc' panicked at 'internal error: generated ill-typed AIR code: error 'in call to %Poly%tuple%0., argument #1 has type "tuple%0." when it should have type "Poly"' in expression '(%Poly%tuple%0. (tuple%0./tuple%0))'', rust_verify/src/verifier.rs:375:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

@Chris-Hawblitzel this is the minimized reproducer for the bug we mentioned a short while ago (not particularly high priority btw, since the fix is to just not have the trivial let binding)

**Comment by tjhance** [comment] 2023-04-10 18:46
I think this is a duplicate of #392. The trait isn't actually necessary for the bug.

**Comment by jaybosamiya** [comment] 2023-04-10 19:17
Ah, I didn't try without the trait (should've run the automated minimizer and that'd have figured out that the trait wasn't necessary).

Anyways, the message here seems to somewhat different (in #392 it seems to be about number of arguments, while here it seems to be the wrong type), so I am not 100% sure it is a duplicate; but indeed seems related.

I suggest leaving this open so that we check this too when we fix up #392.

**Comment by utaal** [comment] 2023-04-11 09:25
It turns out they are slightly different code paths, but conceptually the same issue. https://github.com/verus-lang/verus/commit/f2d802ac331df27dcdafaceeefada1f61b7c8db1 should fix both.

**Comment by utaal** [comment] 2023-04-11 18:41
Fixed in `main_new`.

**Closed by utaal** 2023-04-11 18:41 UTC
Labels: bug
