### ISSUE TITLE
Can't use nat in const context

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#344] opened 2023-01-03 23:54 UTC
This code

```
#![allow(unused_imports)]
use builtin::*;
use builtin_macros::*;

verus! {
pub const RC_WIDTH: nat = 4 as nat;
}

fn main() { }
```

results in

```
error[E0605]: non-primitive cast: `i32` as `builtin::nat`
 --> rust_verify/example/scache/testcase.rs:6:27
  |
6 | pub const RC_WIDTH: nat = 4 as nat;
  |                           ^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object

error: aborting due to previous error

For more information about this error, try `rustc --explain E0605`.
verification results:: verified: 0 errors: 0
```

**Comment by tjhance** [comment] 2023-01-04 22:16
The issue is that the `as nat` is a spec-only feature, so the const needs to be marked spec.

```rust
pub spec const RC_WIDTH: nat = 4 as nat;
```

Perhaps we could have a nicer error message in the syntax macro, though.

**Comment by utaal** [comment] 2023-03-01 10:38
Moved to the error message tracking discussion https://github.com/verus-lang/verus/discussions/387. Closing.

**Closed by utaal** 2023-03-01 10:38 UTC
Labels: question
